Depend on gio-unix-2.0
fcitxtheme.cpp depends on it, and the build will fail if not pulled in
implicitly via somewhere else:

[11/21] Building CXX object gtk4/CMakeFiles/im-fcitx5-gtk4.dir/fcitxtheme.cpp.o
FAILED: gtk4/CMakeFiles/im-fcitx5-gtk4.dir/fcitxtheme.cpp.o
/usr/bin/c++ -Dim_fcitx5_gtk4_EXPORTS -I/buildstream/gnome/sdk/fcitx.bst/_builddir -I/buildstream/gnome/sdk/fcitx.bst/fcitx-gclient/.. -I/buildstream/gnome/sdk/fcitx.bst/_builddir/fcitx-gclient -I/Fcitx5/GClient -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/sysprof-4 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/gtk-4.0 -isystem /usr/include/pango-1.0 -isystem /usr/include/harfbuzz -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/fribidi -isystem /usr/include/cairo -isystem /usr/include/pixman-1 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/graphene-1.0 -isystem /usr/lib/x86_64-linux-gnu/graphene-1.0/include -Wall -Wextra -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -O2 -g -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -mfpmath=sse -msse -msse2 -pthread -std=c++17 -MD -MT gtk4/CMakeFiles/im-fcitx5-gtk4.dir/fcitxtheme.cpp.o -MF gtk4/CMakeFiles/im-fcitx5-gtk4.dir/fcitxtheme.cpp.o.d -o gtk4/CMakeFiles/im-fcitx5-gtk4.dir/fcitxtheme.cpp.o -c /buildstream/gnome/sdk/fcitx.bst/gtk4/fcitxtheme.cpp
/buildstream/gnome/sdk/fcitx.bst/gtk4/fcitxtheme.cpp:12:10: fatal error: gio/gunixinputstream.h: No such file or directory
   12 | #include <gio/gunixinputstream.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.